- name: Downloading Docker GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.asc
  register: gpg
  when: ansible_distribution == 'Ubuntu'

- name: Adding Docker repository to APT
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ distro_name }} stable"
  when: gpg is succeeded and ansible_distribution == 'Ubuntu'
  register: source

- name: Update apt
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker-CE
  apt:
    package: "{{ item.name }}"
  when: source is succeeded and ansible_distribution == 'Ubuntu'
  with_items: "{{ docker_packages }}"
