all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: asean
  children:
    localmachines:
      hosts:
        lucca:
          ansible_port: 22
          ansible_user: asean
          ansible_host: 192.168.0.102
          ansible_password: 12345678
    webservers:
      hosts:
        cartman:
          ansible_port: 2127
          ansible_user: sean
          ansible_host: 157.230.39.173
    nonperm:
      children:
        webservers:
        localmachines:
    desktop:
      children:
        localmachines:





