- name: Initialize new machine
  hosts: lucca
  gather_facts: True
  become: Yes
  tasks:
  roles:
    - var_initialization
    - transfer_ssh_key
    - apt_initialization
    - apt_installation
    - docker_installation
    - dotnet_installation
    - node_installation
    - flatpak_installation
    - git_configuration
    - ssh_configuration
    - security_configuration
