- name: Update apt packages
  apt:
    update_cache: yes

- name: Upgrade apt packages
  apt:
    upgrade: dist

- name: Check distribution if Ubuntu 18
  set_fact:
    packages: "{{ apt_18_packages }}"
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'

- name: Check distribution if Ubuntu 19
  set_fact:
    packages: "{{ apt_19_20_packages }}"
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= 19

- name: Remove unwanted version softwares
  apt:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ packages }}"

- name: Remove unwanted commons softwares
  apt:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ apt_commons_packages }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
