snap_packages_commons:
  - name: ufw
snap_packages_dev:
  - name: postman
  - name: chromium
  - name: dotnet-sdk
    classic: "yes"
  - name: code
    classic: "yes"
  - name: node
    classic: "yes"
    channel: 10/stable
  - name: scrcpy
