- name: Install required apt packages
  apt:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ required_apt_packages }}"

- name: Install desktop apt packages
  apt:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ desktop_apt_packages }}"
  when: "'desktop' in group_names"