git_config:
  - name: "user.name"
    value: "Sean Ervinson"
  - name: "user.email"
    value: "ervinsonong@gmail.com"
  - name: "core.autocrlf"
    value: "no"
  - name: "core.whitespace"
    value: "-trailing-space"
  - name: "core.editor"
    value: "vi"
  - name: "color.status.added"
    value: "green bold"
  - name: "color.status.updated"
    value: "yellow bold"
  - name: "color.status.untracked"
    value: "red bold"
  - name: "color.branch.current"
    value: "yellow bold"
  - name: "color.branch.local"
    value: "green"
  - name: "color.branch.remote"
    value: "cyan"

