- name: Disallow Root Login
  ansible.builtin.lineinfile:
    path: "{{ sshdconfig }}"
    regexp: "^[#]*PermitRootLogin"
    line: "PermitRootLogin no"
    backup: true
    validate: "/usr/sbin/sshd -T -f %s"
  notify: restart sshd

- name: Disallow Password Authentication
  ansible.builtin.lineinfile:
    path: "{{ sshdconfig }}"
    regexp: "^[#]*PasswordAuthentication"
    line: "PasswordAuthentication no"
    backup: true
    validate: "/usr/sbin/sshd -T -f %s"
  notify: restart sshd

- name: Change Default Port
  ansible.builtin.lineinfile:
    path: "{{ sshdconfig }}"
    regexp: "^[#]*Port"
    line: "Port {{ ssh_port }}"
    backup: true
    validate: "/usr/sbin/sshd -T -f %s"
  notify: restart sshd

- name: Allow PublicKey Authentication
  ansible.builtin.lineinfile:
    path: "{{ sshdconfig }}"
    regexp: "^[#]*PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    backup: true
    validate: "/usr/sbin/sshd -T -f %s"
  notify: restart sshd
