- name: Add deafult user
  user:
    name: sean
    comment: Sean Ervinson
    shell: /bin/bash
    groups: docker,sudo
    append: yes
    password: "{{ user_password }}"

- name: Add ci_cd user
  user:
    name: ci_cd
    comment: ci_cd
    shell: /bin/bash
    groups: docker,sudo
    append: yes
    password: "{{ user_password }}"

- name: Add ci_cd user as sudo without password
  lineinfile:
    dest: /etc/sudoers
    line: "ci_cd ALL=(ALL:ALL) NOPASSWD: ALL"
