all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: asean
  children:
    localmachines:
      hosts:
        lucca:
          ansible_port: "{{ ansible_port }}"
          ansible_user: "{{ ansible_user }}"
          ansible_host: "{{ ansible_host }}"
          ansible_password: "{{ vault_ansible_password }}"
    webservers:
      hosts:
        cartman:
          ansible_port: 22
          ansible_user: root
          ansible_host: 64.225.115.111
    nonperm:
      children:
        webservers:
        localmachines:
    desktop:
      children:
        localmachines:
