- name: Download and install fnm
  ansible.builtin.get_url:
    url: https://fnm.vercel.app/install
    dest: /tmp/fnm.sh
    mode: "0755"

- name: Get env fact
  ansible.builtin.setup:
    gather_subset:
      - env

- name: Execute fnm installation script
  ansible.builtin.shell: >
    bash /tmp/fnm.sh -- --skip-shell
  changed_when: true

- name: Install Node LTS
  ansible.builtin.shell: |
    fnm install --lts
  changed_when: true

- name: Install pnpm
  ansible.builtin.shell: |
    corepack enable pnpm
  changed_when: true
