- name: Register Distro Version Id
  ansible.builtin.shell: |
    . /etc/os-release && echo "$VERSION_ID"
  register: distro_version_id
- name: Register Distro Name
  ansible.builtin.shell: |
    . /etc/os-release && echo "$VERSION_CODENAME"
  register: distro_name
- name: Register Distro Version
  ansible.builtin.shell: |
    . /etc/os-release && echo "$VERSION"
  register: distro_version
