all:
  children:
    webservers:
      hosts:
        cartman:
          ansible_port: "{{ ansible_port }}"
          ansible_user: "{{ ansible_user }}"
          ansible_host: "{{ ansible_host }}"
    nonperm:
      children:
        webservers:
