flatpak_packages:
  - name: com.brave.Browser
  - name: com.visualstudio.code
  - name: com.jetbrains.Rider
  - name: com.getpostman.Postman
  - name: org.videolan.VLC
  - name: org.chromium.Chromium
